### ISSUE TITLE
Add RSS feeds for notes and articles

### ISSUE THREAD

**Issue by meduzen** [meduzen/blog#3]
- [x] feed with notes (complete content) #24
- [x] feed with articles (complete content) #24
- [x] feed with articles (excerpt and/or title only) #24
- [x] feed with notes and articles (complete content) #12
- [x] feed with notes and articles (complete content for notes, partial for articles) #24
- [x] show feeds on the front-end #26 

~~Limit it to the last 20 to 40 entries.~~ We’ll decide later, when the blog will have more content.
