### ISSUE TITLE
Add tags on content

### ISSUE THREAD

**Issue by meduzen** [meduzen/blog#4]
- [x] add coma-separated tags to the frontmatter #6 
- [x] show them on the index page #6
- [x] show them on the content page #14
- [x] build index pages `/tags/something` and link tags to these pages #63

**Comment by meduzen** [comment]
All items done, and one moved to its own issue for later #94.

Closing.
